'use strict'
const zlib = require('node:zlib')
const { centroidGeometry } = require('./storm-engine')
const EARTH=6378137, MAX_LAT=85.05112878
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rad=d=>d*Math.PI/180, deg=r=>r*180/Math.PI
function lonLatToWorld(lon,lat,z){const n=2**z,x=(Number(lon)+180)/360*n*256,p=rad(clamp(Number(lat),-MAX_LAT,MAX_LAT)),y=(1-Math.log(Math.tan(p)+1/Math.cos(p))/Math.PI)/2*n*256;return[x,y]}
function lonLatToTilePixel(lon,lat,z,x,y){const p=lonLatToWorld(lon,lat,z);return[p[0]-x*256,p[1]-y*256]}
function destination(point,east,north,seconds){const lon=Number(point[0]),lat=Number(point[1]),de=Number(east||0)*seconds,dn=Number(north||0)*seconds,dlat=dn/EARTH,dlon=de/(EARTH*Math.max(.05,Math.cos(rad(lat))));let outLon=lon+deg(dlon);while(outLon>180)outLon-=360;while(outLon<-180)outLon+=360;return[outLon,clamp(lat+deg(dlat),-90,90)]}
function translateGeometry(g,east,north,seconds){if(!g||!['Polygon','MultiPolygon'].includes(g.type))return null;const mapRing=r=>r.map(p=>destination(p,east,north,seconds));return g.type==='Polygon'?{type:'Polygon',coordinates:g.coordinates.map(mapRing)}:{type:'MultiPolygon',coordinates:g.coordinates.map(poly=>poly.map(mapRing))}}
function cellToHazard(cell,predictionMinutes=[15,30,60]){const centroid=cell.centroid||centroidGeometry(cell.geometry),predictions=centroid?predictionMinutes.filter(m=>m>0).map(minutes=>({minutes,centroid:destination(centroid,cell.motion?.east,cell.motion?.north,minutes*60),geometry:translateGeometry(cell.geometry,cell.motion?.east,cell.motion?.north,minutes*60),uncertaintyMeters:cell.threat?.uncertaintyMeters??null,confidence:cell.motion?.confidence??null,provenance:cell.motion?.method||'tracked-linear'})):[];return{id:String(cell.id),trackId:cell.trackId||String(cell.id),sourceId:cell.sourceId||null,provider:cell.provider||null,product:cell.product||null,time:cell.time||null,state:cell.state||'normal',severity:cell.severity,geometry:cell.geometry,centroid,motion:cell.motion||null,distanceMeters:cell.distanceMeters,cpa:cell.cpa||null,pathThreat:cell.pathThreat||null,threat:cell.threat||null,history:cell.history||[],predictions}}
function hazardsFromCells(cells,predictionMinutes){return{type:'FeatureCollection',generatedAt:new Date().toISOString(),features:(cells||[]).map(c=>{const h=cellToHazard(c,predictionMinutes);return{type:'Feature',id:h.id,geometry:h.geometry,properties:{id:h.id,trackId:h.trackId,sourceId:h.sourceId,provider:h.provider,product:h.product,time:h.time,state:h.state,severity:h.severity,centroid:h.centroid,motion:h.motion,distanceMeters:h.distanceMeters,cpa:h.cpa,pathThreat:h.pathThreat,threat:h.threat,history:h.history},predictions:h.predictions}})}}
const rgba=(r,g,b,a)=>[r,g,b,a]
const STYLES={normal:{stroke:rgba(0,180,220,220),fill:rgba(0,180,220,45)},warn:{stroke:rgba(255,170,0,255),fill:rgba(255,170,0,70)},alarm:{stroke:rgba(235,45,45,255),fill:rgba(235,45,45,90)}}
function blend(buf,x,y,c){if(x<0||y<0||x>=256||y>=256)return;const i=(y*256+x)*4,a=c[3]/255,ia=1-a;buf[i]=Math.round(c[0]*a+buf[i]*ia);buf[i+1]=Math.round(c[1]*a+buf[i+1]*ia);buf[i+2]=Math.round(c[2]*a+buf[i+2]*ia);buf[i+3]=Math.min(255,Math.round(c[3]+buf[i+3]*ia))}
function line(buf,a,b,c,width=2,dashed=false){let x0=Math.round(a[0]),y0=Math.round(a[1]),x1=Math.round(b[0]),y1=Math.round(b[1]),dx=Math.abs(x1-x0),sx=x0<x1?1:-1,dy=-Math.abs(y1-y0),sy=y0<y1?1:-1,e=dx+dy,step=0;for(;;){if(!dashed||Math.floor(step/6)%2===0)for(let yy=-width;yy<=width;yy++)for(let xx=-width;xx<=width;xx++)if(xx*xx+yy*yy<=width*width)blend(buf,x0+xx,y0+yy,c);if(x0===x1&&y0===y1)break;const e2=2*e;if(e2>=dy){e+=dy;x0+=sx}if(e2<=dx){e+=dx;y0+=sy}step++}}
function pointInPoly(x,y,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const xi=ring[i][0],yi=ring[i][1],xj=ring[j][0],yj=ring[j][1];if(((yi>y)!==(yj>y))&&(x<(xj-xi)*(y-yi)/((yj-yi)||1e-9)+xi))inside=!inside}return inside}
function fillRing(buf,ring,c){if(ring.length<3)return;let minX=255,maxX=0,minY=255,maxY=0;for(const p of ring){minX=Math.min(minX,Math.floor(p[0]));maxX=Math.max(maxX,Math.ceil(p[0]));minY=Math.min(minY,Math.floor(p[1]));maxY=Math.max(maxY,Math.ceil(p[1]))}minX=clamp(minX,0,255);maxX=clamp(maxX,0,255);minY=clamp(minY,0,255);maxY=clamp(maxY,0,255);for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++)if(pointInPoly(x+.5,y+.5,ring))blend(buf,x,y,c)}
function projectGeometry(g,z,x,y){const conv=p=>lonLatToTilePixel(p[0],p[1],z,x,y);return g?.type==='Polygon'?g.coordinates.map(r=>r.map(conv)):g?.type==='MultiPolygon'?g.coordinates.flatMap(poly=>poly.map(r=>r.map(conv))):[]}
function drawGeometry(buf,g,z,x,y,style,{fill=true,dashed=false,width=2}={}){for(const ring of projectGeometry(g,z,x,y)){if(fill)fillRing(buf,ring,style.fill);for(let i=1;i<ring.length;i++)line(buf,ring[i-1],ring[i],style.stroke,width,dashed)}}
function crc32(buf){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
function chunk(type,data){const t=Buffer.from(type),len=Buffer.alloc(4),crc=Buffer.alloc(4);len.writeUInt32BE(data.length);crc.writeUInt32BE(crc32(Buffer.concat([t,data])));return Buffer.concat([len,t,data,crc])}
function encodePng(rgbaBuf){const raw=Buffer.alloc((256*4+1)*256);for(let y=0;y<256;y++){const o=y*(256*4+1);raw[o]=0;rgbaBuf.copy(raw,o+1,y*256*4,(y+1)*256*4)}const sig=Buffer.from([137,80,78,71,13,10,26,10]),ihdr=Buffer.alloc(13);ihdr.writeUInt32BE(256,0);ihdr.writeUInt32BE(256,4);ihdr[8]=8;ihdr[9]=6;return Buffer.concat([sig,chunk('IHDR',ihdr),chunk('IDAT',zlib.deflateSync(raw,{level:6})),chunk('IEND',Buffer.alloc(0))])}
function renderHazardTile(cells,z,x,y,{predictionMinutes=[15,30,60]}={}){const buf=Buffer.alloc(256*256*4);for(const cell of cells||[]){if(!cell?.geometry)continue;const s=STYLES[cell.state]||STYLES.normal;drawGeometry(buf,cell.geometry,z,x,y,s,{fill:true,width:cell.state==='alarm'?2:1});const c=cell.centroid||centroidGeometry(cell.geometry);if(c&&cell.motion?.speed>0){const preds=predictionMinutes.map(m=>({m,p:destination(c,cell.motion.east,cell.motion.north,m*60)}));let last=lonLatToTilePixel(c[0],c[1],z,x,y);for(const pr of preds){const p=lonLatToTilePixel(pr.p[0],pr.p[1],z,x,y);line(buf,last,p,s.stroke,1,true);last=p}const final=translateGeometry(cell.geometry,cell.motion.east,cell.motion.north,(predictionMinutes.at(-1)||60)*60);if(final)drawGeometry(buf,final,z,x,y,{stroke:rgba(s.stroke[0],s.stroke[1],s.stroke[2],160),fill:rgba(s.fill[0],s.fill[1],s.fill[2],20)},{fill:false,dashed:true,width:1})}}return encodePng(buf)}
function geometryBounds(g){const pts=[];const walk=v=>{if(Array.isArray(v)&&v.length>=2&&Number.isFinite(Number(v[0]))&&Number.isFinite(Number(v[1])))pts.push([Number(v[0]),Number(v[1])]);else if(Array.isArray(v))v.forEach(walk)};walk(g?.coordinates);if(!pts.length)return null;return[Math.min(...pts.map(p=>p[0])),Math.min(...pts.map(p=>p[1])),Math.max(...pts.map(p=>p[0])),Math.max(...pts.map(p=>p[1]))]}
module.exports={destination,translateGeometry,cellToHazard,hazardsFromCells,renderHazardTile,geometryBounds,lonLatToTilePixel}
